### PR TITLE
Hide tabs in fullscreen

### PR DESCRIPTION
**Pull request by breunigs**

### CODE REVIEW

**Comment by NikolausDemmel** [comment]
Any chance of this getting merged?

**Comment by noscript** [comment]
I personally use [Hide TabBar](https://addons.mozilla.org/en-US/firefox/addon/hide-tabbar/) extension that does that and even more, hiding tab bar when there is only one tab.

**Comment by NikolausDemmel** [comment]
@sergey-vlasov thanks for the hint. I'm currently using the version from this pull request and it works fine for full screen.

**Comment by Croydon** [comment]
If somebody is interested: I merged this into [my fork](https://github.com/Croydon/vertical-tabs-reloaded) of the addon :)

**Pull request closed without merging**
